#!/bin/sh
# Set environment variables. Machine name, username and password set as script parameters.
export MACHINE_NAME=$1

# Sanity check the script run
if (( $# < 1 )); then
    echo Usage: 'create.sh <machine-name>'
    exit 1
fi

# Substitute env params into script template
rm -rf cloud.tf; envsubst < "cloud-template.tem" > "cloud.tf";

# Apply the script.
/usr/bin/terraform apply -input=false -auto-approve
